site_name: Network Topology as a Code
repo_name: kagarcia1618/ntaac
repo_url: "https://github.com/kagarcia1618/ntaac"
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.sections
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - navigation.indexes
    # - navigation.tabs
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: indigo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

copyright: |
  &copy; 2023 <a href="https://github.com/kagarcia1618"  target="_blank" rel="noopener">Kenneth Acar Garcia</a>

nav:
  - Overview: 
    - index.md